apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretsStore.secretProviderClass | default "takeflight-secrets" }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secretsStore.secretName | default "takeflight-app-secrets" | quote }}
        objectType: "secretsmanager"
        jmesPath:
        - path: NEXTAUTH_SECRET
          objectAlias: NEXTAUTH_SECRET
        - path: AUTH_SECRET
          objectAlias: AUTH_SECRET
  secretObjects:
  - secretName: takeflight-secrets
    type: Opaque
    data:
    - objectName: NEXTAUTH_SECRET
      key: NEXTAUTH_SECRET
    - objectName: AUTH_SECRET
      key: AUTH_SECRET