{{- if ne .Release.Namespace "takeflight-preview" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: takeflight-irsa-role
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::015869558327:role/prd-TakeFlightTakeFlightC-TakeFlightClustertakeflig-eFG0xu34TzDx
{{- end }}