{{- if ne .Release.Namespace "takeflight-preview" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: takeflight-preview-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:aligent/take-flight-helm.git
    targetRevision: feature/TF2-21_repository_restructuring
    path: apps/takeflight-preview-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: takeflight-preview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
{{- end }}
