namespace: argocd

server:
  serviceAccount:
    create: false
    name: argocd-blueprints-addon-argocd-server

externalSecrets:
  credentialsType: SSH # or USERNAME
  repoUrl: git@bitbucket.org:aligent/takeflight2.git
  secretName: argocd-repo-creds
  awsSecretName: tf2-argocd-ssh-key
  awsRegion: ap-southeast-2

application:
  name: nextjs-staging
  project: default
  targetRevision: production
  repoUrl: git@bitbucket.org:aligent/takeflight2.git
  path: helm-nextjs/environments/staging/nextjs
  destinationNamespace: nextjs-staging
  server: https://kubernetes.default.svc
