apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: takeflight-feature-previews
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/aligent/take-flight-helm.git
        revision: HEAD
        files:
          - path: "nextjs/preview/**/values.yaml"
  template:
    metadata:
      name: "nextjs-{{ path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/aligent/take-flight-helm.git
        targetRevision: main
        path: nextjs
        helm:
          valueFiles:
            - values.yaml
            - "preview/{{ path.basename }}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
