apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: takeflight-feature-previews
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/aligent/take-flight-helm.git
        revision: main
        directories:
          - path: "nextjs"
        files:
          - path: "nextjs/values-feature-*.yaml"
  template:
    metadata:
      name: "nextjs-{{ basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/aligent/take-flight-helm.git
        targetRevision: main
        path: nextjs
        helm:
          valueFiles:
            - values.yaml
            - values-{{ basename }}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: nextjs-preview-{{ basename }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
