apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: takeflight-feature-previews
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/aligent/take-flight-helm.git
        revision: main
        files:
          - path: "nextjs/values-feature-*.yaml"
  template:
    metadata:
      name: "nextjs-{{ path.filename | replace '.yaml' ''}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/aligent/take-flight-helm.git
        targetRevision: main
        path: nextjs
        helm:
          valueFiles:
            - values.yaml
            - {{ path.filename }}
      destination:
        server: https://kubernetes.default.svc
        namespace: "nextjs-preview-{{ path.filename | replace '.yaml' ''}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
