apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nextjs-previews
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/aligent/take-flight-helm.git
        revision: main
        files:
          - path: nextjs/values-feature-*.yaml
  template:
    metadata:
      name: '{{ path.basename | replace "values-feature-" "" | replace ".yaml" "" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/aligent/take-flight-helm.git
        targetRevision: main
        path: nextjs
        helm:
          valueFiles:
            - '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'feature-{{ path.basename | replace "values-feature-" "" | replace ".yaml" "" }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
