apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: external-dns
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: external-dns
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --source=service
        - --source=ingress
        - --domain-filter={{ .Values.domain }}
        - --provider=aws
        - --policy=upsert-only
        - --aws-zone-type=public
        - --registry=txt
        - --txt-owner-id={{ .Values.txtOwnerId }}
        - --log-level={{ .Values.logLevel }}
        - --interval={{ .Values.interval }}
        {{- if .Values.dryRun }}
        - --dry-run
        {{- end }}
        env:
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.region }}
        - name: AWS_REGION
          value: {{ .Values.region }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL