apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-demo
  namespace: {{ .Release.Namespace }}
  labels:
    app: nextjs-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nextjs-demo
  template:
    metadata:
      labels:
        app: nextjs-demo
    spec:
      serviceAccountName: nextjs-serviceaccount
      containers:
        - name: nextjs-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: "NEXTAUTH_SECRET"
            value: "askldhsaksahksadfhdslkfhdskfhsdkfhkdshfksahkda"
          - name: "NEXTAUTH_URL"
            value: "http://demo.takeflight2.aligent.cloud"
