apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: {{ .Release.Namespace }}
  labels:
    app: nextjs
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      serviceAccountName: nextjs-serviceaccount
      containers:
        - name: nextjs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: "NEXTAUTH_SECRET"
            value: {{ .Values.env.NEXTAUTH_SECRET | quote }}
          - name: "AUTH_SECRET"
            value: {{ .Values.env.AUTH_SECRET | quote }}
          - name: "NEXTAUTH_URL"
            value: {{ .Values.env.NEXTAUTH_URL | quote }}
          - name: "NODE_ENV"
            value: {{ .Values.env.NODE_ENV | quote }}
          - name: "HOST"
            value: {{ .Values.env.HOST | quote }}
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.targetPort }}
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          #   failureThreshold: 10
          #   timeoutSeconds: 2
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.targetPort }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 20
          #   failureThreshold: 5
          #   timeoutSeconds: 2