apiVersion: v1
kind: Service
metadata:
  name: nextjs-demo
  namespace: {{ .Release.Namespace }}
  labels:
    app: nextjs-demo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.hostname }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: nextjs-demo
