replicaCount: 2
revisionHistoryLimit: 3

image:
  repository: "aligent/takeflight2-nextjs-docker"
  # repository: "aaronmedinaaligent/my-nextjs-app"
  tag: "feature-5b92b26"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: true
  hostname: "feature-5b92b26.takeflight2.aligent.cloud"
  certarn: "arn:aws:acm:ap-southeast-2:182399723872:certificate/30f1ca2f-35f4-44bb-919a-d902569eb0f5"
