replicaCount: 2  # Number of pods to run

image:
  repository: "aaronmedinaaligent/my-nextjs-app"  # Public Next.js image
  tag: "latest"  # Use the latest tag
  pullPolicy: Always  # Always pull the latest image

service:
  type: "LoadBalancer"
  port: 80
  targetPort: 3000
  annotations:
    externalDnsHostname: "nextjs.takeflight2.aligent.cloud"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
