apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.application.project }}
  source:
    repoURL: {{ .Values.application.repoUrl }}
    targetRevision: {{ .Values.application.targetRevision }}
    path: {{ .Values.application.path }}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: {{ .Values.application.server }}
    namespace: {{ .Values.application.destinationNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true