# Default values for takeflight
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 0

image:
  repository: "aligent/takeflight-nextjs-docker"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: true
  hostname: ""
  certarn: "arn:aws:acm:ap-southeast-2:015869558327:certificate/4a18f727-3164-4481-892b-9716dcae5a60"

secrets:
  create: false
  name: "takeflight-secrets"

secretsStore:
  secretProviderClass: "takeflight-secrets"
  secretName: "takeflight-secrets"

env:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
