# Default values for takeflight
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Main store configuration (disabled by default - only Storybook hosts by default)
mainStore:
  enabled: false

replicaCount: 1
revisionHistoryLimit: 0

image:
  repository: "aligent/takeflight-nextjs-docker"
  tag: "latest" # won't be used
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: true
  hostname: "store.takeflight.aligent.cloud"
  certarn: "arn:aws:acm:ap-southeast-2:015869558327:certificate/4a18f727-3164-4481-892b-9716dcae5a60"

secrets:
  create: true
  name: "takeflight-secrets"

secretsStore:
  secretProviderClass: "takeflight-secrets"
  secretName: "takeflight-secrets"

env:
  NEXTAUTH_URL: "https://store.takeflight.aligent.cloud"
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  DEBUG: "1"
  NEXT_DEBUG: "1"

# Storybook service configuration
storybook:
  enabled: true
  replicaCount: 1
  image:
    repository: "aligent/takeflight-nextjs-docker"
    tag: "storybook-b72e213"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    limits:
      cpu: "250m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  ingress:
    hostname: "storybook.takeflight.aligent.cloud"

# AWS Load Balancer Controller configuration
awsLoadBalancerController:
  enable: true
  clusterName: "TakeFlight-Cluster"
  region: "ap-southeast-2"
  vpcId: ""  # Will be populated by ArgoCD parameters
  serviceAccount:
    name: "aws-load-balancer-controller"
  image:
    repository: "602401143452.dkr.ecr.ap-southeast-2.amazonaws.com/amazon/aws-load-balancer-controller"

# External DNS configuration
externalDns:
  enable: true
  domain: "takeflight.aligent.cloud"
  zoneId: "Z03717161X319SNYY1IIX"
  region: "ap-southeast-2"

# Target revision for ApplicationSet (overridden by ArgoCD parameter)
targetRevision: "feature/TF2-21_repository_restructuring"

