apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ui-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aligent/take-flight-helm.git
    targetRevision: main
    path: environments/staging/argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
