replicaCount: 2
revisionHistoryLimit: 2

image:
  repository: "aligent/takeflight2-nextjs-docker"
  # repository: "aaronmedinaaligent/my-nextjs-app"
  tag: "staging-1746494271"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: true
  hostname: "demo.takeflight2.aligent.cloud"
  certarn: "arn:aws:acm:ap-southeast-2:182399723872:certificate/171401ce-1512-40ab-a624-8ad557849a64"

env:
  NEXTAUTH_SECRET: "askldhsaksahksadfhdslkfhdskfhsdkfhkdshfksahkda"
  AUTH_SECRET: "askldhsaksahksadfhdslkfhdskfhsdkfhkdshfksahkda"
  NEXTAUTH_URL: "http://demo.takeflight2.aligent.cloud"
  NODE_ENV: "production"
  HOST: "0.0.0.0"


