apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: argocd
  template:
    metadata:
      name: '{{name}}-self-managed'
    spec:
      project: default
      source:
        repoURL: https://github.com/aligent/take-flight-helm.git
        targetRevision: main
        path: environments/staging-argo
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
